### ISSUE TITLE
[Bug]: expose self-update not working

### ISSUE THREAD

**Issue by schonhoff** [exposedev/expose#440]
### System architecture

Windows

### PHP Version

Herd Version 1.15.0 with PHP 8.3.17

### Bug description

Hey,

trying the documented command `expose self-update` isn't working as expected. In my global composer.json is the following:

```json
{
    "require": {
        "friendsofphp/php-cs-fixer": "^3.0",
        "beyondcode/expose": "^2.3",
        "laravel/installer": "^5.9"
    }
}
```

If I don't change anything the command will output:

```bash
expose self-update

Checking for a new version...
=============================

                                                                                                                        
 [OK] You have the latest version installed.       
```

If I change the composer.json to the following:
```json
{
    "require": {
        "friendsofphp/php-cs-fixer": "^3.0",
        "laravel/installer": "^5.9",
        "exposedev/expose": "^3.0"
    }
}
```

and use composer global update it will output:

```bash
composer global update -W
Changed current directory to C:/Users/schon/AppData/Roaming/Composer
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires exposedev/expose ^3.0 -> satisfiable by exposedev/expose[3.0.0, 3.0.1].
    - exposedev/expose[3.0.0, ..., 3.0.1] require cboden/ratchet dev-master -> found cboden/ratchet[dev-master] but it does not match your minimum-stability.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

After that I tried thisn change:

```json
{
    "require": {
        "friendsofphp/php-cs-fixer": "^3.0",
        "laravel/installer": "^5.9",
        "exposedev/expose": "^3.0"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```
output:
```bash
composer global update -W
Changed current directory to C:/Users/schon/AppData/Roaming/Composer
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires exposedev/expose ^3.0 -> satisfiable by exposedev/expose[3.0.0, 3.0.1].
    - exposedev/expose[3.0.0, ..., 3.0.1] require react/http dev-websocket-support -> found react/http[v0.1.0, ..., v0.8.7, v1.0.0, ..., 1.x-dev, 3.x-dev] but it does not match the constraint.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```
```bash
expose self-update

Checking for a new version...
=============================
                                                                                                                        
 [OK] You have the latest version installed.         
```

Sometimes I get the log output below. But I cannot reproduce this sadly :/

What am I missing?

### Relevant log output

```shell
expose self-update

Checking for a new version...
=============================

PHP Fatal error:  Uncaught ErrorException: include(): zlib: data error in phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php:571
Stack trace:
#0 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'include(): zlib...', 'phar://C:/Users...', 571)
#1 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php(571): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(8, 'include(): zlib...', 'phar://C:/Users...', 571)
#2 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php(571): include('phar://C:/Users...')
#3 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('phar://C:/Users...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Illuminate\\Foun...')
#5 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/illuminate/container/Container.php(889): ReflectionClass->__construct('Illuminate\\Foun...')
#6 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build('Illuminate\\Foun...')
#7 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(862): Illuminate\Container\Container->resolve('Illuminate\\Foun...', Array, false)
#8 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/illuminate/container/Container.php(295): Illuminate\Foundation\Application->resolve('Illuminate\\Foun...', Array, false)      
#9 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/illuminate/container/Container.php(885): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(LaravelZero\Framework\Application), Array)
#10 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build(Object(Closure))
#11 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(862): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#12 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/illuminate/container/Container.php(706): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#13 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(847): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#14 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(299): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#15 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(218): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#16 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(204): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole(Object(ErrorException))
#17 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#18 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(ErrorException))
#19 {main}
  thrown in phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php on line 571
PHP Fatal error:  Uncaught ErrorException: include(): zlib: data error in phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php:571
Stack trace:
#0 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'include(): zlib...', 'phar://C:/Users...', 571)
#1 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php(571): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(8, 'include(): zlib...', 'phar://C:/Users...', 571)
#2 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php(571): include('phar://C:/Users...')
#3 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('phar://C:/Users...')
#4 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#5 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(242): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalErrorFromPhpError(Array, 0)
#6 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#7 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#8 {main}
  thrown in phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php on line 571
```

**Comment by schonhoff** [comment]
Here is my php.ini (needed to change it to .txt because of Github uploads...

[php.txt](https://github.com/user-attachments/files/18907122/php.txt)

**Comment by daugaard47** [comment]
On windows I cannot run `expose self-update` either.

```
In Updater.php line 417:

  rename(C:\Users\dauga\.config\herd\bin/expose.phar.temp,C:\Users\dauga\.config\herd\bin\expose.phar): Access is den
  ied (code: 5)
```


I've been an expose pro user before herd came out so I removed my global beyond code version and global exposedev version and rely on Herd expose now. 

To get it to work in 3.0.1 I had to download the repo and do the following

- Add .phar extension to the expose file in the builds folder
- Remove the existing expose.phar in Herd's bin directory | `C:\Users\dauga\.config\herd\bin\expose.phar`
- Move the new expose.phar to Herd's bin directory
- herd restart
- Now expose is updated, but reverts back once I close down and reopen herd

I ended up creating a script to do this to save time.
Now I will have to do the same thing, but since 3.0.2 has direct access to the expose.phar file I can remove a couple steps above.

> @mpociot  Please put out a windows herd update with the new Expose version.

**Here is the script that I run in case anyone want to do this. (Use at your own risk!)**

1. Just download the new `expose.phar` file [from here](https://github.com/exposedev/expose/blob/21ca78b6e5e2918b3b3dbd9c7cd06b942f446856/builds/expose.phar)
2. Add it to your `herd` directory
3. Create a UpdateExpose3-2.bat file on your desktop
4. Copy the below and change `your-name-here` to your windows username
5. Run as Admin

```
@echo off
echo Updating Expose for Herd...

:: Copy the original expose binary to preserve it
copy "C:\Users\your-name-here\Herd\expose\builds\expose" "C:\Users\your-name-here\Herd\expose\builds\expose_copy" /Y

:: Rename the copied file to expose.phar
rename "C:\Users\your-name-here\Herd\expose\builds\expose_copy" "expose.phar"

:: Remove the existing expose.phar in Herd's bin directory
del "C:\Users\your-name-here\.config\herd\bin\expose.phar" /F /Q

:: Move the new expose.phar to Herd's bin directory
move "C:\Users\your-name-here\Herd\expose\builds\expose.phar" "C:\Users\your-name-here\.config\herd\bin\expose.phar"

:: Verify the updated version
php C:\Users\your-name-here\.config\herd\bin\expose.phar --version

:: Restart Herd
herd restart

:: Verify Expose after restart
expose --version

echo Update complete! Press any key to exit...
pause >nul

```

![Image](https://github.com/user-attachments/assets/a79ccd68-f2ad-4aea-85be-cc8d027f95f2)

Here is the full error.
[expose-self-update-windows-error.txt](https://github.com/user-attachments/files/18914803/expose-self-update-windows-error.txt)

**Comment by rosswintle** [comment]
I'm trying to do an update from Expose v2 to v3 and I'm getting the same output that @schonhoff got:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires beyondcode/expose ^3.0 -> satisfiable by beyondcode/expose[3.0.0, 3.0.1, 3.0.2].
    - beyondcode/expose[3.0.0, ..., 3.0.2] require react/http dev-websocket-support -> found react/http[v0.1.0, ..., v0.8.7, v1.0.0, ..., 1.x-dev, 3.x-dev] but it does not match the constraint.
```

The required constraint `dev-websocket-support` no longer exists as a tag or branch of https://github.com/reactphp/http

**Comment by IE-Dev** [comment]
I encountered the same error as @schonhoff. To resolve it, I installed the extension `php{version}-zip`, which fixed the initial issue.

However, I then faced another error: `production.ERROR: could not find driver (Connection: sqlite`. To address this, I installed `php{version}-sqlite3`.

After installing both extensions, all issues were resolved.

I hope this helps others facing similar problems 😄

**Comment by schonhoff** [comment]
It is not fixed for me. Tried it again with `expose self-update` but got this:
```bash
Checking for a new version...
=============================

PHP Fatal error:  Uncaught ErrorException: include(): zlib: data error in phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php:576
Stack trace:
#0 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'include(): zlib...', 'phar://C:/Users...', 576)
#1 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php(576): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(8, 'include(): zlib...', 'phar://C:/Users...', 576)
#2 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php(576): include('phar://C:/Users...')
#3 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('phar://C:/Users...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Illuminate\\Foun...')
#5 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/illuminate/container/Container.php(959): ReflectionClass->__construct('Illuminate\\Foun...')
#6 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/illuminate/container/Container.php(832): Illuminate\Container\Container->build('Illuminate\\Foun...')
#7 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(1025): Illuminate\Container\Container->resolve('Illuminate\\Foun...', Array, false)
#8 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/illuminate/container/Container.php(324): Illuminate\Foundation\Application->resolve('Illuminate\\Foun...', Array, false)
#9 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/illuminate/container/Contai
ner.php(952): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(LaravelZero\Framework\Application), Array)
#10 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/illuminate/container/Container.php(832): Illuminate\Container\Container->build(Object(Closure))
#11 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(1025): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#12 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/illuminate/container/Container.php(763): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#13 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(1010): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#14 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/sr
c/Illuminate/Foundation/Bootstrap/HandleExceptions.php(289): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#15 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/sr
c/Illuminate/Foundation/Bootstrap/HandleExceptions.php(208): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#16 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/sr
c/Illuminate/Foundation/Bootstrap/HandleExceptions.php(190): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole(Object(ErrorException))
#17 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/sr
c/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#18 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(ErrorException))
#19 {main}
  thrown in phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php on line 576
PHP Fatal error:  Uncaught ErrorException: include(): zlib: data error in phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php:576
Stack trace:
#0 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src
/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'include(): zlib...', 'phar://C:/Users...', 576)
#1 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.p
hp(576): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(8, 'include(): zlib...', 'phar://C:/Users...', 576)
#2 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php(576): include('phar://C:/Users...')
#3 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('phar://C:/Users...')
#4 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src
/Illuminate/Foundation/Bootstrap/HandleExceptions.php(245): Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#5 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src
/Illuminate/Foundation/Bootstrap/HandleExceptions.php(232): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalErrorFromPhpError(Array, 0)
#6 phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/vendor/laravel-zero/foundation/src
/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#7 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()     
#8 {main}
  thrown in phar://C:/Users/schon/AppData/Roaming/Composer/vendor/exposedev/expose/builds/expose/.box/vendor/composer/ClassLoader.php on line 576
```

My PHP version is 8.3.19 from Herd. My extensions are:

```ini
extension=bz2

; The ldap extension must be before curl if OpenSSL 1.0.2 and OpenLDAP is used
; otherwise it results in segfault when unloading after using SASL.
; See https://github.com/php/php-src/issues/8620 for more info.
;extension=ldap

extension=curl
extension=ffi
;extension=ftp
extension=fileinfo
extension=gd
;extension=gettext
extension=gmp
extension=intl
;extension=imap
extension=mbstring
extension=exif      ; Must be after mbstring as it depends on it
extension=mysqli
;extension=oci8_12c  ; Use with Oracle Database 12c Instant Client
;extension=oci8_19  ; Use with Oracle Database 19 Instant Client
;extension=odbc
extension=openssl
;extension=pdo_firebird
extension=pdo_mysql
;extension=pdo_oci
;extension=pdo_odbc
extension=pdo_pgsql
extension=pdo_sqlite
extension=pgsql
extension=shmop

; The MIBS data available in the PHP distribution must be installed.
; See https://www.php.net/manual/en/snmp.installation.php
;extension=snmp

extension=soap
extension=sockets
extension=sodium
extension=sqlite3
;extension=tidy
;extension=xsl
extension=zip
```

Don't know what to do. I will try the manual update and post the result later.

**Comment by rosswintle** [comment]
This updated fine for me using `composer global update`.

Thanks!
